[package]
name = "c22_p1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "unsafe_operations"
path = "src/unsafe_operations.rs"
