[package]
name = "c20_8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "foreign_function_interface"
path = "src/foreign_function_interface.rs"
