[package]
name = "c9_2_6_p2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "examples_in_std"
path = "src/examples_in_std.rs"
