[package]
name = "c18_5_4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "other_use_of_question_mark"
path = "src/other_use_of_question_mark.rs"
