[package]
name = "c17_4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "variadic_interfaces"
path = "src/variadic_interfaces.rs"
