[package]
name = "c1_2_2_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "testcase-list"
path = "src/testcase-list.rs"
