[package]
name = "c18_5_5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "wrapping_errors"
path = "src/wrapping_errors.rs"
