[package]
name = "c8_5_1_4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "pointer_and_ref"
path = "src/pointer_and_ref.rs"
