[package]
name = "c2_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "arrays_and_slices"
path = "src/arrays_and_slices.rs"
