[package]
name = "c18_4_1_p1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "map_for_result"
path = "src/map_for_result.rs"
