[package]
name = "c18_5_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "defining_an_error_type"
path = "src/defining_an_error_type.rs"
