workspace = { members = ["c19_5_1"] }
[package]
name = "c19_5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "result"
path = "src/result.rs"
