[package]
name = "c18_3_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "combinators_and_then"
path = "src/combinators_and_then.rs"
