[package]
name = "c10_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "struct_visibility"
path = "src/struct_visibility.rs"
