[package]
name = "c18_2_p2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "abort_and_unwind"
path = "src/abort_and_unwind.rs"
