[package]
name = "c9_2_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "type_anonymity"
path = "src/type_anonymity.rs"
