[package]
name = "c6_3_p2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "parsing_a_string"
path = "src/parsing_a_string.rs"
