[package]
name = "c_20_4_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "read_lines"
path = "src/read_lines.rs"
