[package]
name = "c15_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "ownership_and_moves"
path = "src/ownership_and_moves.rs"
