[package]
name = "c15_4_8_p2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "reference_lifetime"
path = "src/reference_lifetime.rs"
